---
- name: Create Service for Sonarr
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: v1
      kind: Service
      metadata:
        name: sonarr-svc
        namespace: "{{ sonarr_namespace }}"
      spec:
        ports:
          - name: http
            port: 80
            targetPort: 8989
        selector:
          app: sonarr
