---
- name: Create Let's Encrypt Certificate for Sonarr
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: cert-manager.io/v1
      kind: Certificate
      metadata:
        name: "sonarr-cert-{{ letsencrypt_environment }}"
        namespace: "{{ sonarr_namespace }}"
      spec:
        secretName: "sonarr-{{ letsencrypt_environment }}-tls"
        issuerRef:
          name: "letsencrypt-{{ letsencrypt_environment }}"
          kind: ClusterIssuer
        commonName: "{{ sonarr_domain }}"
        dnsNames:
          - "{{ sonarr_domain }}"
