# file:
# synopsis:
---
- name: Create Persistent Volume Claim for Sonarr configuration files
  kubernetes.core.k8s:
    state: present
    definition:
      kind: PersistentVolumeClaim
      apiVersion: v1
      metadata:
        name: sonarr-config-pvc
        namespace: "{{ sonarr_namespace }}"
      spec:
        storageClassName: longhorn-rwx
        accessModes:
          - ReadWriteMany
        resources:
          requests:
            storage: 2Gi

- name: Create Sonarr Persistent Volume Claim for data NFS share
  kubernetes.core.k8s:
    state: present
    definition:
      kind: PersistentVolumeClaim
      apiVersion: v1
      metadata:
        name: sonarr-data-pvc
        namespace: "{{ sonarr_namespace }}"
      spec:
        volumeName: sonarr-data-pv
        storageClassName: ""
        accessModes:
          - ReadWriteMany
        resources:
          requests:
            storage: 8Ti # Dummy value
