# file: ./inventory/prod/hosts.yaml
# synopsis: configuration used by Ansible.
---
all:
  children:
    openhab4:
      hosts:
        openhab:
          host_address: 10.100.3.112
          ansible_user: openhab
    # The node IP addresses are predefined as reserved IPs (based on MAC address) in the DHCP server.
    kube:
      children:
        master:
          hosts:
            k3s-prod-m01:
              host_address: 10.100.3.21
            k3s-prod-m02:
              host_addres: 10.100.3.22
            k3s-prod-m03:
              host_address: 10.100.3.123
        worker:
          hosts:
            k3s-prod-w01:
              host_address: 10.100.3.24
              disk1: ata-Samsung_SSD_870_QVO_8TB_S5SSNF0RC00820E
              disk2: ata-Samsung_SSD_870_QVO_8TB_S5SSNF0RC00828H
              disk3: ata-Samsung_SSD_870_QVO_8TB_S5SSNF0T301077P
              disk4: ata-Samsung_SSD_870_QVO_8TB_S5SSNJ0R401327R
            k3s-prod-w02:
              host_address: 10.100.3.25
              disk1: ata-Samsung_SSD_870_QVO_8TB_S5SSNF0T402544J
              disk2: ata-Samsung_SSD_870_QVO_8TB_S5SSNF0T405646X
              disk3: ata-Samsung_SSD_870_QVO_8TB_S5SSNF0T405649P
              disk4: ata-Samsung_SSD_870_QVO_8TB_S5SSNF0T405651D
            k3s-prod-w03:
              host_address: 10.100.3.26
              disk1: ata-Samsung_SSD_870_QVO_8TB_S5SSNJ0T102126P
              disk2: ata-Samsung_SSD_870_QVO_8TB_S5SSNJ0T102173N
              disk3: ata-Samsung_SSD_870_QVO_8TB_S5SSNF0T301086X
              disk4: ata-Samsung_SSD_870_QVO_8TB_S5SSNF0T405643E
