---
- name: Create Let's Encrypt Certificate for SABnzbd
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: cert-manager.io/v1
      kind: Certificate
      metadata:
        name: "sabnzbd-cert-{{ letsencrypt_environment }}"
        namespace: "{{ sabnzbd_namespace }}"
      spec:
        secretName: "sabnzbd-{{ letsencrypt_environment }}-tls"
        issuerRef:
          name: "letsencrypt-{{ letsencrypt_environment }}"
          kind: ClusterIssuer
        commonName: "{{ sabnzbd_domain }}"
        dnsNames:
          - "{{ sabnzbd_domain }}"
