---
- name: Create SABnzbd PV for media files NFS share
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: v1
      kind: PersistentVolume
      metadata:
        name: sabnzbd-downloads-pv
      spec:
        persistentVolumeReclaimPolicy: Retain
        capacity:
          storage: 10Mi # Dummy value
        accessModes:
          - ReadWriteMany
        nfs:
          path: /media/usenet
          server: 10.0.0.2
        mountOptions:
          - nolock
