---
- name: Create SABnzbd Persistent Volume for media SMB3 share
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: v1
      kind: PersistentVolume
      metadata:
        name: sabnzbd-data-pv
      spec:
        storageClassName: ""
        capacity:
          storage: 10Ti
        accessModes:
          - ReadWriteMany
        persistentVolumeReclaimPolicy: Retain
        mountOptions:
          - dir_mode=0777
          - file_mode=0777
          - uid=1000
          - gid=1000
          - vers=3.0
        csi:
          driver: smb.csi.k8s.io
          readOnly: false
          volumeHandle: sabnzbd_share_volid  # make sure it's a unique id in the cluster
          volumeAttributes:
            source: "//{{ nas_address }}/{{ smb_media_share }}"
          nodeStageSecretRef:
            name: smbcreds
            namespace: default
