# file:
# synopsis:
---
- name: Create Longhorn RWX Storage class
  kubernetes.core.k8s:
    state: present
    definition:
      kind: StorageClass
      apiVersion: storage.k8s.io/v1
      metadata:
        name: longhorn-rwx
      provisioner: driver.longhorn.io
      allowVolumeExpansion: true
      reclaimPolicy: Delete
      volumeBindingMode: Immediate
      parameters:
        numberOfReplicas: "3"
        staleReplicaTimeout: "2880"
        fromBackup: ""
        fsType: "ext4"
        nfsOptions: "hard,timeo=50,retrans=1"

- name: Create SABnzbd Persistent Volume Claim for configuration files
  kubernetes.core.k8s:
    state: present
    definition:
      kind: PersistentVolumeClaim
      apiVersion: v1
      metadata:
        name: sabnzbd-config-pvc
        namespace: "{{ sabnzbd_namespace }}"
      spec:
        storageClassName: longhorn-rwx
        accessModes:
          - ReadWriteMany
        resources:
          requests:
            storage: 2Gi

- name: Create SABnzbd Persistent Voluem Claim for incomplete downloads
  kubernetes.core.k8s:
    state: present
    definition:
      kind: PersistentVolumeClaim
      apiVersion: v1
      metadata:
        name: sabnzbd-incomplete-downloads-pvc
        namespace: "{{ sabnzbd_namespace }}"
      spec:
        storageClassName: longhorn
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 400Gi

- name: Create SABnzbd Persistent Volume Claim for completed downloads share
  kubernetes.core.k8s:
    state: present
    definition:
      kind: PersistentVolumeClaim
      apiVersion: v1
      metadata:
        name: sabnzbd-data-pvc
        namespace: "{{ sabnzbd_namespace }}"
      spec:
        volumeName: sabnzbd-data-pv
        storageClassName: ""
        accessModes:
          - ReadWriteMany
        resources:
          requests:
            storage: 8Ti # Dummy value
