# file:
---
- name: Create SABnzbd Pod Deployment
  kubernetes.core.k8s:
    state: present
    definition:
      kind: Deployment
      apiVersion: apps/v1
      metadata:
        name: sabnzbd
        labels:
          app: sabnzbd
        namespace: "{{ sabnzbd_namespace }}"
      spec:
        progressDeadlineSeconds: 300
        replicas: 1
        serviceName: sabnzbd-app
        revisionHistoryLimit: 0
        strategy:
          rollingUpdate:
            maxSurge: 1
            maxUnavailable: 1
          type: RollingUpdate
        selector:
          matchLabels:
            app: sabnzbd
        template:
          metadata:
            labels:
              app: sabnzbd
          spec:
            containers:
              - name: sabnzbd
                image: "{{ sabnzbd_image_registry }}/sabnzbd:{{ sabnzbd_image_tag }}"
                imagePullPolicy: IfNotPresent
                resources:
                  limits:
                    memory: "4096Mi"
                    cpu: 4000m
                  requests:
                    memory: "2048Mi"
                    cpu: 500m
                livenessProbe:
                  httpGet:
                    path: /
                    port: 8080
                  initialDelaySeconds: 60
                  periodSeconds: 30
                ports:
                  - name: nzb-web
                    containerPort: 8080
                volumeMounts:
                  - name: sabnzbd-config
                    mountPath: /config
                  - name: sabnzbd-incomplete-downloads
                    mountPath: /incomplete-downloads
                  - name: sabnzbd-downloads
                    mountPath: /data/usenet
                env:
                  - name: PUID
                    value: "1000"
                  - name: PGID
                    value: "1000"
                  - name: TZ
                    value: Europe/Amsterdam
                  - name: HOST_WHITELIST_ENTRIES
                    value: "{{ sabnzbd_domain }}, sabnzbd-svc"
            volumes:
              - name: sabnzbd-config
                persistentVolumeClaim:
                  claimName: sabnzbd-config-pvc
              - name: sabnzbd-incomplete-downloads
                persistentVolumeClaim:
                  claimName: sabnzbd-incomplete-downloads-pvc
              - name: sabnzbd-downloads
                persistentVolumeClaim:
                  claimName: sabnzbd-downloads-pvc
            serviceName: sabnzbd-app
            revisionHistoryLimit: 0
