# qm create 8001 --memory 4096 --cores 2 --name debian-12-cloudinit --net0 virtio,bridge=vmbr100
# qm importdisk 8001 debian-12-genericcloud-amd64-20230910-1499.qcow2 local-lvm
# qm set 8001 --scsihw virtio-scsi-pci --scsi0 local-lvm:vm-8001-disk-0
# qm set 8001 --ide2 local-lvm:cloudinit
# qm set 8001 --boot c --bootdisk scsi0
# qm set 8001 --serial0 socket --vga serial0
# Fill in the cloud-init details
# Create template
# Repeat on other hosts
---
- name: Delete VM node 1 + 4 of cluster nodes
  shell: |
    qm stop 2001
    qm stop 2004
    qm destroy 2001
    qm destroy 2004
  delegate_to: prox01
  ignore_errors: true
  register: destroy

- name: Delete VM node 2 + 5 of cluster nodes
  shell: |
    qm stop 2002
    qm stop 2005
    qm destroy 2002
    qm destroy 2005
  delegate_to: prox02
  ignore_errors: true
  register: destroy

- name: Delete VM node 3 + 6 of cluster nodes
  shell: |
    qm stop 2003
    qm stop 2006
    qm destroy 2003
    qm destroy 2006
  delegate_to: prox03
  ignore_errors: true
  register: destroy
