# ---
vm_master_nodes: [1, 2, 1]
vm_master_template: "{{ ci_template_name }}"
vm_worker_nodes: [1, 2]
vm_worker_template: "{{ ci_template_name }}"

# master_nodes:
#   - m01:
#       node: prox01
#       template: "{{ ci_template_name }}"
#       vmid: 8001
#       newid: 2001
#       memory: 12288
#       disk_size: 107374182400
#       ostype: l26
#       cores: 6
#       virtio: { 'virtio0': 'local-lvm:100,format=raw' }
#       mac: '02:be:10:64:03:21'
#       brdige: 'vmbr100'
#   - m02:
#       node: prox02
#       template: "{{ ci_template_name }}"
#       vmid: 8002
#       newid: 2002
#       memory: 12288
#       disk_size: 107374182400
#       cores: 6
#       virtio: '{"virtio0": "local-lvm:100,format=raw"}'
#       mac: '02:be:10:64:03:22'
#       brdige: 'vmbr100'
#   - m03:
#       node: prox01
#       template: "{{ ci_template_name }}"
#       vmid: 8001
#       newid: 2003
#       memory: 12288
#       disk_size: 107374182400
#       cores: 6
#       virtio: '{"virtio0": "local-lvm:100,format=raw"}'
#       mac: '02:be:10:64:03:23'
#       brdige: 'vmbr100'
# worker_nodes:
#   - w01:
#       node: prox01
#       template: "{{ ci_template_name }}"
#       vmid: 8001
#       newid: 2004
#       memory: 16384
#       disk_size: 107374182400
#       cores: 6
#       virtio: { 'virtio0': 'local-lvm:100,format=raw' }
#       mac: '02:be:10:64:03:24'
#       brdige: 'vmbr100'
#   - w02:
#       node: prox02
#       template: "{{ ci_template_name }}"
#       vmid: 8002
#       newid: 2005
#       memory: 16384
#       disk_size: 107374182400
#       cores: 6
#       virtio: { 'virtio0': 'local-lvm:100,format=raw' }
#       mac:  '02:be:10:64:03:25'
#       brdige: 'vmbr100'
