---
- name: Create Cloudflare token secret
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: v1
      kind: Secret
      metadata:
        name: cloudflare-token-secret
        namespace: cert-manager
      type: Opaque
      stringData:
        cloudflare-token: "{{ cloudflare_secret }}"
