---
- name: Create Let's Encrypt ClusterIssuer(s)
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: cert-manager.io/v1
      kind: ClusterIssuer
      metadata:
        name: "{{ item.name }}"
      spec:
        acme:
          email: "{{ item.email }}"
          server: "https://{{ item.server }}.api.letsencrypt.org/directory"
          privateKeySecretRef:
            name: "{{ item.private_key_secret_ref_name }}"
          solvers:
            - dns01:
                cloudflare:
                  email: "{{ item.email }}"
                  apiTokenSecretRef:
                    name: cloudflare-token-secret
                    key: cloudflare-token
              selector:
                dnsZones: "{{ le_dns_zones }}"
  loop: "{{ cert_manager_le_clusterissuer_options }}"
  when: cert_manager_le_clusterissuer_options is defined

- name: Create Certificate ClusterIssuer for self-signed certificates
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: cert-manager.io/v1
      kind: ClusterIssuer
      metadata:
        name: "{{ cert_manager_self_signed }}"
        namespace: cert-manager
      spec:
        selfSigned: {}
