---
- name: Create Let's Encrypt Certificate for Bazarr
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: cert-manager.io/v1
      kind: Certificate
      metadata:
        name: "bazarr-cert-{{ letsencrypt_environment }}"
        namespace: "{{ bazarr_namespace }}"
      spec:
        secretName: "bazarr-{{ letsencrypt_environment }}-tls"
        issuerRef:
          name: "letsencrypt-{{ letsencrypt_environment }}"
          kind: ClusterIssuer
        commonName: "{{ bazarr_domain }}"
        dnsNames:
          - "{{ bazarr_domain }}"
