---
- name: Create Service for Bazarr
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: v1
      kind: Service
      metadata:
        name: bazarr-svc
        namespace: "{{ bazarr_namespace }}"
      spec:
        ports:
          - name: http
            port: 80
            targetPort: 6767
        selector:
          app: bazarr
