# file:
---
- name: Create Bazarr Deployment
  kubernetes.core.k8s:
    state: present
    definition:
      kind: Deployment
      apiVersion: apps/v1
      metadata:
        name: bazarr
        labels:
          app: bazarr
        namespace: "{{ bazarr_namespace }}"
      spec:
        progressDeadlineSeconds: 300
        replicas: 1
        serviceName: bazarr-app
        revisionHistoryLimit: 0
        strategy:
          rollingUpdate:
            maxSurge: 1
            maxUnavailable: 1
          type: RollingUpdate
        selector:
          matchLabels:
            app: bazarr
        template:
          metadata:
            labels:
              app: bazarr
          spec:
            containers:
              - name: bazarr
                image: "{{ bazarr_image_registry }}/bazarr:{{ bazarr_image_tag }}"
                imagePullPolicy: IfNotPresent
                resources:
                  limits:
                    memory: "2048Mi"
                    cpu: 1000m
                  requests:
                    memory: "256Mi"
                    cpu: 200m
                livenessProbe:
                  httpGet:
                    path: /
                    port: 6767
                  initialDelaySeconds: 60
                  periodSeconds: 30
                ports:
                  - name: http
                    containerPort: 6767
                volumeMounts:
                  - name: bazarr-config
                    mountPath: /config
                  - name: bazarr-tv
                    mountPath: /tv
                  - name: bazarr-movies
                    mountPath: /movies
                env:
                  - name: PUID
                    value: "1000"
                  - name: PGID
                    value: "1000"
                  - name: TZ
                    value: Europe/Amsterdam
            volumes:
              - name: bazarr-config
                persistentVolumeClaim:
                  claimName: bazarr-config-pvc
              - name: bazarr-tv
                persistentVolumeClaim:
                  claimName: bazarr-tv-pvc
              - name: bazarr-movies
                persistentVolumeClaim:
                  claimName: bazarr-movies-pvc
            serviceName: bazarr-app
            revisionHistoryLimit: 0
