---
- name: Create Radarr Persistent Volume for media SMB3 share
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: v1
      kind: PersistentVolume
      metadata:
        name: radarr-data-pv
      spec:
        storageClassName: ""
        capacity:
          storage: 10Ti # Dummy value
        accessModes:
          - ReadWriteMany
        persistentVolumeReclaimPolicy: Retain
        mountOptions:
          - dir_mode=0777
          - file_mode=0777
          - vers=3.0
          - uid=1000
          - gid=1000
        csi:
          driver: smb.csi.k8s.io
          readOnly: false
          volumeHandle: "{{ radarr_share_volid }}"
          volumeAttributes:
            source: "//{{ nas_address }}/{{ smb_media_share }}"
          nodeStageSecretRef:
            name: smbcreds
            namespace: default
