---
- name: Create Let's Encrypt Certificate for radarr
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: cert-manager.io/v1
      kind: Certificate
      metadata:
        name: "radarr-cert-{{ letsencrypt_environment }}"
        namespace: "{{ radarr_namespace }}"
      spec:
        secretName: "radarr-{{ letsencrypt_environment }}-tls"
        issuerRef:
          name: "letsencrypt-{{ letsencrypt_environment }}"
          kind: ClusterIssuer
        commonName: "{{ radarr_domain }}"
        dnsNames:
          - "{{ radarr_domain }}"
