---
- name: Create K3s directory if it does not exist
  ansible.builtin.file:
    path: /etc/rancher/k3s
    state: directory
    mode: '0755'
    owner: root
    group: root

- name: Copy registries file to all nodes
  ansible.builtin.template:
    src: "registries.yaml.j2"
    dest: "/etc/rancher/k3s/registries.yaml"
    owner: root
    group: root
    mode: 0644
  notify:
    - Restart K3s
