---
- name: Create Let's Encrypt Certificate for qBittorrent
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: cert-manager.io/v1
      kind: Certificate
      metadata:
        name: "qbittorrent-cert-{{ letsencrypt_environment }}"
        namespace: "{{ qbittorrent_namespace }}"
      spec:
        secretName: "qbittorrent-{{ letsencrypt_environment }}-tls"
        issuerRef:
          name: "letsencrypt-{{ letsencrypt_environment }}"
          kind: ClusterIssuer
        commonName: "{{ qbittorrent_domain }}"
        dnsNames:
          - "{{ qbittorrent_domain }}"
