# file:
---
- name: Create Prowlarr Deployment
  kubernetes.core.k8s:
    state: present
    definition:
      kind: Deployment
      apiVersion: apps/v1
      metadata:
        name: prowlarr
        labels:
          app: prowlarr
        namespace: "{{ prowlarr_namespace }}"
      spec:
        progressDeadlineSeconds: 300
        replicas: 1
        serviceName: prowlarr-app
        revisionHistoryLimit: 0
        strategy:
          rollingUpdate:
            maxSurge: 1
            maxUnavailable: 1
          type: RollingUpdate
        selector:
          matchLabels:
            app: prowlarr
        template:
          metadata:
            labels:
              app: prowlarr
          spec:
            containers:
              - name: prowlarr
                image: "{{ prowlarr_image_registry }}/prowlarr:{{ prowlarr_image_tag }}"
                imagePullPolicy: IfNotPresent
                resources:
                  limits:
                    memory: "2096Mi"
                    cpu: 1000m
                  requests:
                    memory: "1024Mi"
                    cpu: 200m
                livenessProbe:
                  httpGet:
                    path: /
                    port: 9696
                  initialDelaySeconds: 60
                  periodSeconds: 30
                ports:
                  - name: http
                    containerPort: 9696
                volumeMounts:
                  - name: prowlarr-config
                    mountPath: /config
                env:
                  - name: PUID
                    value: "1000"
                  - name: PGID
                    value: "1000"
                  - name: TZ
                    value: Europe/Amsterdam
            volumes:
              - name: prowlarr-config
                persistentVolumeClaim:
                  claimName: prowlarr-config-pvc
            serviceName: prowlarr-app
            revisionHistoryLimit: 0
