---
- name: Create local .kube directory
  ansible.builtin.file:
    path: /Users/Ron/.kube
    state: directory
    mode: 0775
  delegate_to: localhost
  become: false

- name: Copy config file to local .kube directory
  ansible.builtin.fetch:
    src: "/home/{{ shell_user }}/.kube/config"
    dest: "/Users/Ron/.kube/"
    flat: true
  become: false
  when: inventory_hostname == hostvars[groups[group_name_master | default('master')][0]]['ansible_hostname']
