---
- name: Create Bosch XMPP Deployment
  kubernetes.core.k8s:
    state: present
    definition:
      kind: Deployment
      apiVersion: apps/v1
      metadata:
        name: bosch-xmpp
        labels:
          app: bosch-xmpp
        namespace: "{{ openhab_namespace }}"
      spec:
        selector:
          matchLabels:
            app: bosch-xmpp
        template:
          metadata:
            labels:
              app: bosch-xmpp
          spec:
            containers:
            - name: bosch-xmpp
              image: "{{ bosch_xmpp_image_registry }}/{{ bosch_xmpp_image_name }}:{{ bosch_xmpp_image_tag }}"
              imagePullPolicy: IfNotPresent
              ports:
              - containerPort: 3000
  delegate_to: 127.0.0.1
  run_once: true
