---
# Namespace to deploy qBittorrent into
qbittorrent_namespace: default
# External URL to access qBittorrent through Traefik
qbittorrent_domain: "torrent.{{ main_domain }}"
# qBittorrent container info
qbittorrent_image_registry: "{{ private_registry }}"
qbittorrent_image_tag: 4.6.2
# Unique Volume ID for qBittorrent SMB3 share
qbittorrent_share_volid: "torrent-media-share"
